import { MedicationCatalogModel, ResearchArticleModel } from "../models";

const medicationCatalogSeed = [
  {
    slug: "semaglutide-generic",
    name: "Semaglutide",
    drugClass: "glp_1",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [0.25, 0.5, 1, 1.7, 2.4],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 0.25,
    active: true,
  },
  {
    slug: "ozempic",
    name: "Ozempic",
    brand: "Ozempic",
    drugClass: "glp_1",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [0.25, 0.5, 1, 2],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 0.25,
    active: true,
  },
  {
    slug: "wegovy",
    name: "Wegovy",
    brand: "Wegovy",
    drugClass: "glp_1",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [0.25, 0.5, 1, 1.7, 2.4],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 0.25,
    active: true,
  },
  {
    slug: "compounded-semaglutide",
    name: "Compounded semaglutide",
    drugClass: "glp_1",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [0.25, 0.5, 1, 1.7, 2.4],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 0.25,
    active: true,
  },
  {
    slug: "oral-semaglutide",
    name: "Oral semaglutide",
    drugClass: "glp_1",
    route: "oral",
    defaultFrequency: "daily",
    commonDoses: [3, 7, 14],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 3,
    active: true,
  },
  {
    slug: "rybelsus",
    name: "Rybelsus",
    brand: "Rybelsus",
    drugClass: "glp_1",
    route: "oral",
    defaultFrequency: "daily",
    commonDoses: [3, 7, 14],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 3,
    active: true,
  },
  {
    slug: "wegovy-pill",
    name: "Wegovy Pill",
    brand: "Wegovy",
    drugClass: "glp_1",
    route: "oral",
    defaultFrequency: "daily",
    commonDoses: [25, 50],
    halfLifeDays: 7,
    doseUnit: "mg",
    defaultDose: 25,
    active: true,
  },
  {
    slug: "trulicity",
    name: "Trulicity",
    brand: "Trulicity",
    drugClass: "glp_1",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [0.75, 1.5, 3, 4.5],
    halfLifeDays: 5,
    doseUnit: "mg",
    defaultDose: 0.75,
    active: true,
  },
  {
    slug: "tirzepatide-generic",
    name: "Tirzepatide",
    drugClass: "dual_glp_1_gip",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [2.5, 5, 7.5, 10, 12.5, 15],
    halfLifeDays: 5,
    doseUnit: "mg",
    defaultDose: 2.5,
    active: true,
  },
  {
    slug: "mounjaro",
    name: "Mounjaro",
    brand: "Mounjaro",
    drugClass: "dual_glp_1_gip",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [2.5, 5, 7.5, 10, 12.5, 15],
    halfLifeDays: 5,
    doseUnit: "mg",
    defaultDose: 2.5,
    active: true,
  },
  {
    slug: "zepbound",
    name: "Zepbound",
    brand: "Zepbound",
    drugClass: "dual_glp_1_gip",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [2.5, 5, 7.5, 10, 12.5, 15],
    halfLifeDays: 5,
    doseUnit: "mg",
    defaultDose: 2.5,
    active: true,
  },
  {
    slug: "compounded-tirzepatide",
    name: "Compounded tirzepatide",
    drugClass: "dual_glp_1_gip",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [2.5, 5, 7.5, 10, 12.5, 15],
    halfLifeDays: 5,
    doseUnit: "mg",
    defaultDose: 2.5,
    active: true,
  },
  {
    slug: "research-peptide",
    name: "Research peptide",
    drugClass: "peptide",
    route: "injection",
    defaultFrequency: "weekly",
    commonDoses: [],
    halfLifeDays: 3,
    doseUnit: "mg",
    active: true,
  },
] as const;

const researchArticleSeed = [
  {
    slug: "semaglutide-step-1",
    title: "Once-weekly semaglutide in adults with overweight or obesity",
    summary:
      "STEP 1 trial context for semaglutide weight-loss outcomes and tolerability.",
    url: "https://pubmed.ncbi.nlm.nih.gov/?term=once-weekly+semaglutide+adults+overweight+obesity+STEP+1",
    source: "PubMed",
    category: "glp_1",
    publishedAt: "2021-03-18",
  },
  {
    slug: "tirzepatide-surmount-1",
    title: "Tirzepatide once weekly for the treatment of obesity",
    summary: "SURMOUNT-1 trial context for tirzepatide weight-loss outcomes.",
    url: "https://pubmed.ncbi.nlm.nih.gov/?term=SURMOUNT-1+tirzepatide+obesity",
    source: "PubMed",
    category: "glp_1",
    publishedAt: "2022-07-21",
  },
  {
    slug: "protein-during-weight-loss",
    title: "Higher protein diets and lean mass during weight loss",
    summary:
      "Research background on protein intake as a lever for preserving lean mass.",
    url: "https://pubmed.ncbi.nlm.nih.gov/?term=higher+protein+diet+lean+mass+weight+loss",
    source: "PubMed",
    category: "muscle_retention",
  },
  {
    slug: "resistance-training-weight-loss",
    title: "Resistance training and lean mass preservation during weight loss",
    summary:
      "Research background on resistance training as a muscle-retention signal.",
    url: "https://pubmed.ncbi.nlm.nih.gov/?term=resistance+training+lean+mass+preservation+weight+loss",
    source: "PubMed",
    category: "muscle_retention",
  },
  {
    slug: "glp1-gastrointestinal-effects",
    title: "Gastrointestinal effects with GLP-1 receptor agonists",
    summary:
      "Clinical context for common side effects including nausea and constipation.",
    url: "https://pubmed.ncbi.nlm.nih.gov/?term=GLP-1+receptor+agonist+gastrointestinal+adverse+events",
    source: "PubMed",
    category: "side_effects",
  },
] as const;

export async function seedCatalogs(): Promise<void> {
  await Promise.all(
    medicationCatalogSeed.map((item) =>
      MedicationCatalogModel.updateOne(
        { slug: item.slug },
        { $set: item },
        { upsert: true },
      ),
    ),
  );
  await Promise.all(
    researchArticleSeed.map((article) =>
      ResearchArticleModel.updateOne(
        { slug: article.slug },
        { $set: article },
        { upsert: true },
      ),
    ),
  );
}
